language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

env:
    global:
        - secure: "A6KrBr8rkdpmD2G11pvOXwuw92V5pnSwXS9zINcn6AyTMzoPyW2i6yLZvwzTYI1u2kxgj2yuaR47zIr7MlGEDMqJc7S/k7JxHHCE20n6bmXsqte2brJirdz4CHDOAQIX9ODWq7qOS+YKHRZPWRu6K16RmQAdnFOnB04XuMo0U9Y="
    matrix:
        - TRAVIS_BUILD_TYPE=Debug
        - TRAVIS_BUILD_TYPE=Release

cache: apt

install:
    # Store root directory
    - export TRAV_ROOT=$(pwd)/..
    # Store project root
    - export PROJ_ROOT=$(pwd)

    # Install icub
    - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
    - sudo apt-get update
    - sudo apt-get --force-yes install icub

    # Install icub-contrib
    - export ICUBcontrib_DIR=$TRAV_ROOT/iCubContrib
    - cd $TRAV_ROOT
    - git clone https://github.com/robotology/icub-contrib-common.git
    - cd icub-contrib-common
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$ICUBcontrib_DIR
    - make
    - sudo make install
    - cd $TRAV_ROOT

    # Install doxygen
#    - sudo apt-get --force-yes install doxygen
    -  wget http://mirrors.kernel.org/ubuntu/pool/main/d/doxygen/doxygen_1.8.4-1_amd64.deb
    - sudo dpkg -i ./doxygen_1.8.4-1_amd64.deb
    - sudo apt-get -f install 

before_script:
    - cd $PROJ_ROOT
    - cmake --version
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE}

script:
#    # Build project
#    - make
#    - sudo make install

    # Create doxygen documentation
    - cd $PROJ_ROOT
    - doxygen conf/Doxyfile

after_success:
    # Publish doxygen documentation
    - cd $PROJ_ROOT
    - chmod -R 744 .travis
    - .travis/push-doxygen-to-gh-pages.sh
